import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "@/app/components/navbar/navbar";
import LineNumber from "@/app/components/linenumber/lineNumber";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-row h-full">
        <div className="w-[4%] h-full">
          <NavBar/>
        </div>
        <div className="w-[3%] h-full">
          <LineNumber/>
        </div>
        <div className="w-[97%] h-full p-5">
          {children}
        </div>
      </body>
    </html>
  )
}
